import type { Level } from "./types";

const layers = {
  showShotAngle: true,
  showBallLine: true,
  showNearPost: true,
  showSuggestedMove: true,
  showShotTrajectories: true,
  showPassTrajectory: true,
  showDistances: true
};

const baseLevels: Level[] = [
  {
    id: "angle-right-half",
    title: "Мяч справа у штрафной",
    category: "shot_angle",
    difficulty: 2,
    ball: { x: 68, y: 24 },
    players: [{ id: "a1", role: "attacker", x: 68, y: 27, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 4 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Отлично: ближний угол справа под контролем.",
    almostText: "Почти: смещение верное, но глубину можно выбрать точнее.",
    errorText: "Разберем: мяч справа, а ближний угол остался слишком открытым.",
    hintText: "Проверь ближний угол справа.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "angle-left-wide",
    title: "Острый угол слева",
    category: "shot_angle",
    difficulty: 3,
    ball: { x: 22, y: 16 },
    players: [{ id: "a1", role: "attacker", x: 22, y: 18, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 4 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Верно: ты сместился к мячу и закрыл ближнюю штангу.",
    almostText: "Почти: ближний угол почти закрыт, но позиция чуть центральная.",
    errorText: "Разберем: с острого угла сначала закрывай ближнюю штангу.",
    hintText: "Мяч слева - ближний угол тоже слева.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "depth-long-center",
    title: "Дальний удар по центру",
    category: "depth",
    difficulty: 2,
    ball: { x: 50, y: 42 },
    players: [{ id: "a1", role: "attacker", x: 50, y: 45, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "TOO_DEEP",
    successText: "Хорошая глубина: ты не застрял на линии.",
    almostText: "Почти: направление верное, выйди чуть выше.",
    errorText: "Разберем: ты слишком глубоко, нападающий видит много ворот.",
    hintText: "Мяч далеко - можно стоять выше.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "depth-close-center",
    title: "Близкий удар по центру",
    category: "depth",
    difficulty: 3,
    ball: { x: 50, y: 12 },
    players: [{ id: "a1", role: "attacker", x: 50, y: 14, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 8 },
    mainErrorType: "TOO_HIGH",
    successText: "Отлично: ты готов к удару и не выбежал слишком далеко.",
    almostText: "Почти: позиция рабочая, но будь чуть ближе к воротам.",
    errorText: "Разберем: при близком мяче нельзя улетать слишком высоко.",
    hintText: "Близкий мяч - остановись перед ударом.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "one-v-one-center",
    title: "Выход 1-в-1 по центру",
    category: "one_v_one",
    difficulty: 4,
    ball: { x: 51, y: 23 },
    players: [{ id: "a1", role: "attacker", x: 51, y: 25, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 1.5 },
    mainErrorType: "PASSIVE_1V1",
    successText: "Сильное решение: ты сократил угол и остановился перед ударом.",
    almostText: "Почти: выход правильный, но точку можно выбрать спокойнее.",
    errorText: "Разберем: в 1-в-1 нельзя пассивно оставаться на линии.",
    hintText: "Сократи угол, но не бросайся.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "defender-pressure-right",
    title: "Защитник давит справа",
    category: "defender_pressure",
    difficulty: 4,
    ball: { x: 66, y: 20 },
    players: [
      { id: "a1", role: "attacker", x: 66, y: 22, hasBall: true },
      { id: "d1", role: "defender", x: 62, y: 20, label: "D" }
    ],
    initialGoalkeeper: { x: 50, y: 5 },
    mainErrorType: "IGNORED_DEFENDER",
    successText: "Верно: защитник давит, ты держишь ворота и угол.",
    almostText: "Почти: угол закрыт, но не выходи слишком рано.",
    errorText: "Разберем: защитник рядом, поэтому ранний рывок открывает ворота.",
    hintText: "Посмотри, успевает ли защитник.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "pass-left-center",
    title: "Пас слева в центр",
    category: "pass_reposition",
    difficulty: 4,
    ball: { x: 50, y: 18 },
    previousBall: { x: 24, y: 16 },
    players: [
      { id: "a1", role: "attacker", x: 24, y: 16 },
      { id: "a2", role: "attacker", x: 50, y: 20, hasBall: true }
    ],
    initialGoalkeeper: { x: 39, y: 5 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: мяч ушел в центр, и ты перестроился вместе с ним.",
    almostText: "Почти: ты начал перестроение, но не дошел до линии мяча.",
    errorText: "Разберем: мяч уже в центре, старая позиция больше не подходит.",
    hintText: "После паса ищи новую линию мяча.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "cross-right-far-post",
    title: "Прострел справа",
    category: "pass_reposition",
    difficulty: 5,
    ball: { x: 76, y: 8 },
    previousBall: { x: 76, y: 22 },
    players: [
      { id: "a1", role: "attacker", x: 76, y: 8, hasBall: true },
      { id: "a2", role: "attacker", x: 42, y: 7 }
    ],
    initialGoalkeeper: { x: 50, y: 3 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Класс: ты закрыл ближний угол и готов к прострелу.",
    almostText: "Почти: ближний угол под контролем, но глубина немного спорная.",
    errorText: "Разберем: при простреле сначала не открывай ближнюю штангу.",
    hintText: "Справа у лицевой - ближняя штанга решает.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "two-attackers-center",
    title: "Два нападающих по центру",
    category: "one_v_one",
    difficulty: 4,
    ball: { x: 48, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 48, y: 25, hasBall: true },
      { id: "a2", role: "attacker", x: 60, y: 21 }
    ],
    initialGoalkeeper: { x: 50, y: 3 },
    mainErrorType: "PASSIVE_1V1",
    successText: "Хорошо: ты сократил угол к игроку с мячом и готов к пасу.",
    almostText: "Почти: позиция близка, но проверь глубину перед возможным пасом.",
    errorText: "Разберем: при двух нападающих нельзя застревать на линии ворот.",
    hintText: "Сначала закрой игрока с мячом, но помни про передачу рядом.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "three-attackers-edge",
    title: "Три игрока перед штрафной",
    category: "defender_pressure",
    difficulty: 5,
    ball: { x: 57, y: 30 },
    players: [
      { id: "a1", role: "attacker", x: 57, y: 31, hasBall: true },
      { id: "a2", role: "attacker", x: 42, y: 24 },
      { id: "a3", role: "attacker", x: 70, y: 22 },
      { id: "d1", role: "defender", x: 53, y: 28 }
    ],
    initialGoalkeeper: { x: 50, y: 4 },
    mainErrorType: "IGNORED_DEFENDER",
    successText: "Верно: ты держишь линию мяча и не выбегаешь без причины.",
    almostText: "Почти: направление хорошее, но позиция должна быть спокойнее.",
    errorText: "Разберем: вокруг несколько вариантов паса, поэтому важна равновесная позиция.",
    hintText: "Оцени, может ли игрок ударить сейчас или скорее отдаст пас.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "two-v-one-left-pass",
    title: "2-в-1, пас налево",
    category: "pass_reposition",
    difficulty: 5,
    ball: { x: 35, y: 18 },
    previousBall: { x: 52, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 52, y: 24 },
      { id: "a2", role: "attacker", x: 35, y: 18, hasBall: true },
      { id: "d1", role: "defender", x: 48, y: 21 }
    ],
    initialGoalkeeper: { x: 50, y: 6 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: пас ушел налево, и ты быстро перестроился.",
    almostText: "Почти: ты начал движение за пасом, но ближний угол еще открыт.",
    errorText: "Разберем: после передачи новая опасность уже слева.",
    hintText: "После паса забудь старую точку мяча и найди новую линию.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  }
];

const extraLevels: Level[] = [
  {
    id: "angle-right-wide",
    title: "Широко справа",
    category: "shot_angle",
    difficulty: 3,
    ball: { x: 78, y: 18 },
    players: [{ id: "a1", role: "attacker", x: 78, y: 20, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 4 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Отлично: ближняя штанга справа закрыта.",
    almostText: "Почти: смещение верное, но стань чуть спокойнее по глубине.",
    errorText: "Разберем: с такого угла нельзя открывать ближнюю штангу.",
    hintText: "Мяч очень справа - сначала ближняя штанга.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "angle-left-half",
    title: "Мяч слева у штрафной",
    category: "shot_angle",
    difficulty: 2,
    ball: { x: 32, y: 24 },
    players: [{ id: "a1", role: "attacker", x: 32, y: 27, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 4 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Хорошо: ты сместился к мячу и закрыл левый угол.",
    almostText: "Почти: направление верное, но можно точнее закрыть угол.",
    errorText: "Разберем: мяч слева, а ближний угол слева открыт.",
    hintText: "Проверь левую ближнюю штангу.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "angle-center-medium",
    title: "Удар по центру",
    category: "shot_angle",
    difficulty: 1,
    ball: { x: 50, y: 24 },
    players: [{ id: "a1", role: "attacker", x: 50, y: 27, hasBall: true }],
    initialGoalkeeper: { x: 42, y: 4 },
    mainErrorType: "TOO_LEFT",
    successText: "Верно: мяч по центру, и ты держишь центр ворот.",
    almostText: "Почти: не уходи далеко в сторону, когда мяч по центру.",
    errorText: "Разберем: при мяче по центру нельзя уходить от середины.",
    hintText: "Мяч по центру - вратарь тоже почти по центру.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "depth-far-right",
    title: "Дальний удар справа",
    category: "depth",
    difficulty: 3,
    ball: { x: 64, y: 43 },
    players: [{ id: "a1", role: "attacker", x: 64, y: 45, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "TOO_DEEP",
    successText: "Хорошая глубина: ты вышел выше и держишь угол.",
    almostText: "Почти: выйди еще немного выше.",
    errorText: "Разберем: при дальнем ударе ты слишком близко к линии ворот.",
    hintText: "Мяч далеко - можно стоять смелее.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "depth-far-left",
    title: "Дальний удар слева",
    category: "depth",
    difficulty: 3,
    ball: { x: 36, y: 43 },
    players: [{ id: "a1", role: "attacker", x: 36, y: 45, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "TOO_DEEP",
    successText: "Верно: ты вышел выше и сместился к мячу.",
    almostText: "Почти: смещение есть, но глубина еще осторожная.",
    errorText: "Разберем: далеко от ворот - не застревай на линии.",
    hintText: "Сместись к мячу и выйди выше.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "depth-close-right",
    title: "Близкий удар справа",
    category: "depth",
    difficulty: 4,
    ball: { x: 62, y: 11 },
    players: [{ id: "a1", role: "attacker", x: 62, y: 13, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 9 },
    mainErrorType: "TOO_HIGH",
    successText: "Отлично: ты закрыл угол и не выбежал лишнего.",
    almostText: "Почти: будь чуть ближе к воротам перед ударом.",
    errorText: "Разберем: мяч близко, слишком высокий выход рискован.",
    hintText: "Близко к воротам - готовься к удару.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "one-v-one-right",
    title: "1-в-1 справа",
    category: "one_v_one",
    difficulty: 4,
    ball: { x: 63, y: 22 },
    players: [{ id: "a1", role: "attacker", x: 63, y: 24, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 1.5 },
    mainErrorType: "PASSIVE_1V1",
    successText: "Сильно: ты вышел навстречу и сократил угол.",
    almostText: "Почти: выход хороший, но точка немного неточная.",
    errorText: "Разберем: в 1-в-1 справа нужно выйти и закрыть угол.",
    hintText: "Выходи навстречу, но остановись перед ударом.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "one-v-one-left",
    title: "1-в-1 слева",
    category: "one_v_one",
    difficulty: 4,
    ball: { x: 37, y: 22 },
    players: [{ id: "a1", role: "attacker", x: 37, y: 24, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 1.5 },
    mainErrorType: "PASSIVE_1V1",
    successText: "Верно: ты сократил угол и не остался на линии.",
    almostText: "Почти: направление верное, но точку можно выбрать точнее.",
    errorText: "Разберем: нельзя ждать на линии, когда нападающий свободен.",
    hintText: "Сократи угол к игроку с мячом.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "one-v-one-heavy-touch",
    title: "1-в-1, мяч отпущен вперед",
    category: "one_v_one",
    difficulty: 5,
    ball: { x: 52, y: 17 },
    players: [{ id: "a1", role: "attacker", x: 52, y: 24, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "PASSIVE_1V1",
    successText: "Отлично: мяч отпущен, можно смелее сократить угол.",
    almostText: "Почти: идея верная, но выход можно сделать активнее.",
    errorText: "Разберем: когда мяч отпущен, у вратаря есть шанс выйти.",
    hintText: "Мяч дальше от ноги - можно быть смелее.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "defender-lost-center",
    title: "Защитник проигран",
    category: "defender_pressure",
    difficulty: 4,
    ball: { x: 52, y: 20 },
    players: [
      { id: "a1", role: "attacker", x: 52, y: 22, hasBall: true },
      { id: "d1", role: "defender", x: 43, y: 25 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "PASSIVE_1V1",
    successText: "Верно: защитник уже не успевает, ты защищаешь пространство.",
    almostText: "Почти: нужно чуть активнее сократить угол.",
    errorText: "Разберем: защитник проигран, вратарю нельзя быть пассивным.",
    hintText: "Если защитник сзади, вратарь помогает смелее.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "defender-blocks-shot",
    title: "Защитник перекрывает удар",
    category: "defender_pressure",
    difficulty: 4,
    ball: { x: 58, y: 19 },
    players: [
      { id: "a1", role: "attacker", x: 58, y: 21, hasBall: true },
      { id: "d1", role: "defender", x: 55, y: 18 }
    ],
    initialGoalkeeper: { x: 50, y: 8 },
    mainErrorType: "IGNORED_DEFENDER",
    successText: "Хорошо: защитник мешает удару, ты держишь ворота.",
    almostText: "Почти: не выходи слишком резко, защитник уже рядом.",
    errorText: "Разберем: при давлении защитника ранний выход может открыть ворота.",
    hintText: "Смотри не только на мяч, но и на защитника.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "pass-right-center",
    title: "Пас справа в центр",
    category: "pass_reposition",
    difficulty: 4,
    ball: { x: 50, y: 18 },
    previousBall: { x: 76, y: 16 },
    players: [
      { id: "a1", role: "attacker", x: 76, y: 16 },
      { id: "a2", role: "attacker", x: 50, y: 20, hasBall: true }
    ],
    initialGoalkeeper: { x: 61, y: 5 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: ты вернулся к новой линии мяча.",
    almostText: "Почти: перестроение началось, но нужно точнее.",
    errorText: "Разберем: пас изменил линию мяча, старая позиция больше не подходит.",
    hintText: "После паса ищи новую линию мяча.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "cutback-left",
    title: "Откат с левого фланга",
    category: "pass_reposition",
    difficulty: 5,
    ball: { x: 45, y: 14 },
    previousBall: { x: 22, y: 8 },
    players: [
      { id: "a1", role: "attacker", x: 22, y: 8 },
      { id: "a2", role: "attacker", x: 45, y: 14, hasBall: true }
    ],
    initialGoalkeeper: { x: 40, y: 3 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Верно: ты перестроился под откат в центр.",
    almostText: "Почти: не оставайся у ближней штанги после отката.",
    errorText: "Разберем: мяч откатили назад, позиция у штанги уже не главная.",
    hintText: "Откат назад - новая угроза по центру.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "cutback-right",
    title: "Откат с правого фланга",
    category: "pass_reposition",
    difficulty: 5,
    ball: { x: 55, y: 14 },
    previousBall: { x: 78, y: 8 },
    players: [
      { id: "a1", role: "attacker", x: 78, y: 8 },
      { id: "a2", role: "attacker", x: 55, y: 14, hasBall: true }
    ],
    initialGoalkeeper: { x: 60, y: 3 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Хорошо: ты не остался у ближней штанги после отката.",
    almostText: "Почти: линия мяча уже ближе к центру.",
    errorText: "Разберем: после отката нужно уходить от старого угла.",
    hintText: "Новый мяч - новая позиция.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "far-post-run",
    title: "Передача на дальнюю штангу",
    category: "pass_reposition",
    difficulty: 5,
    ball: { x: 38, y: 8 },
    previousBall: { x: 75, y: 10 },
    players: [
      { id: "a1", role: "attacker", x: 75, y: 10 },
      { id: "a2", role: "attacker", x: 38, y: 8, hasBall: true }
    ],
    initialGoalkeeper: { x: 61, y: 3 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: ты успел сместиться к дальней штанге.",
    almostText: "Почти: перестройся быстрее к новой стороне.",
    errorText: "Разберем: мяч уже у другой штанги, старая позиция опасна.",
    hintText: "Следи за мячом до конца передачи.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "three-attackers-left",
    title: "Трое атакуют слева",
    category: "defender_pressure",
    difficulty: 5,
    ball: { x: 34, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 34, y: 25, hasBall: true },
      { id: "a2", role: "attacker", x: 47, y: 18 },
      { id: "a3", role: "attacker", x: 62, y: 20 },
      { id: "d1", role: "defender", x: 39, y: 23 }
    ],
    initialGoalkeeper: { x: 50, y: 4 },
    mainErrorType: "TOO_CENTRAL",
    successText: "Верно: ты сместился к мячу и готов к пасу в центр.",
    almostText: "Почти: позиция рабочая, но ближний угол требует внимания.",
    errorText: "Разберем: когда атака слева, нельзя оставаться строго по центру.",
    hintText: "Закрой ближний угол и держи передачу перед собой.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "three-attackers-right",
    title: "Трое атакуют справа",
    category: "defender_pressure",
    difficulty: 5,
    ball: { x: 66, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 66, y: 25, hasBall: true },
      { id: "a2", role: "attacker", x: 53, y: 18 },
      { id: "a3", role: "attacker", x: 38, y: 20 },
      { id: "d1", role: "defender", x: 61, y: 23 }
    ],
    initialGoalkeeper: { x: 50, y: 4 },
    mainErrorType: "TOO_CENTRAL",
    successText: "Хорошо: ты сместился к мячу и контролируешь угол.",
    almostText: "Почти: не забывай про ближнюю штангу справа.",
    errorText: "Разберем: атака справа, а позиция слишком центральная.",
    hintText: "Мяч справа - смещайся вправо.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "central-overload",
    title: "Перегруз перед воротами",
    category: "defender_pressure",
    difficulty: 5,
    ball: { x: 50, y: 26 },
    players: [
      { id: "a1", role: "attacker", x: 50, y: 27, hasBall: true },
      { id: "a2", role: "attacker", x: 42, y: 17 },
      { id: "a3", role: "attacker", x: 58, y: 17 },
      { id: "d1", role: "defender", x: 48, y: 23 },
      { id: "d2", role: "defender", x: 55, y: 21 }
    ],
    initialGoalkeeper: { x: 43, y: 3 },
    mainErrorType: "TOO_LEFT",
    successText: "Верно: при угрозе по центру ты держишь центральную линию.",
    almostText: "Почти: вернись ближе к середине линии мяча.",
    errorText: "Разберем: мяч по центру, уход в сторону открывает ворота.",
    hintText: "При центральной угрозе держи центр.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "late-pass-right",
    title: "Поздний пас направо",
    category: "pass_reposition",
    difficulty: 5,
    ball: { x: 68, y: 15 },
    previousBall: { x: 50, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 50, y: 24 },
      { id: "a2", role: "attacker", x: 68, y: 15, hasBall: true },
      { id: "d1", role: "defender", x: 57, y: 21 }
    ],
    initialGoalkeeper: { x: 50, y: 6 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: ты увидел поздний пас и сместился вправо.",
    almostText: "Почти: перестроение верное, но ближний угол еще открыт.",
    errorText: "Разберем: после паса направо нужно сместиться к новой угрозе.",
    hintText: "Не смотри на старую точку мяча.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "late-pass-left",
    title: "Поздний пас налево",
    category: "pass_reposition",
    difficulty: 5,
    ball: { x: 32, y: 15 },
    previousBall: { x: 50, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 50, y: 24 },
      { id: "a2", role: "attacker", x: 32, y: 15, hasBall: true },
      { id: "d1", role: "defender", x: 43, y: 21 }
    ],
    initialGoalkeeper: { x: 50, y: 6 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Хорошо: ты сместился к новому мячу слева.",
    almostText: "Почти: нужно чуть точнее закрыть левый угол.",
    errorText: "Разберем: мяч ушел налево, а позиция осталась старой.",
    hintText: "Пас налево - новая линия мяча тоже налево.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "corner-right-near-post",
    title: "Угловой справа",
    category: "corner",
    difficulty: 5,
    ball: { x: 94, y: 2 },
    players: [
      { id: "a1", role: "attacker", x: 94, y: 3, hasBall: true },
      { id: "a2", role: "attacker", x: 58, y: 10 },
      { id: "d1", role: "defender", x: 53, y: 8 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    goalTarget: { side: -0.35, depth: 0.9 },
    mainErrorType: "TOO_RIGHT",
    successText: "Отлично: ты стоишь между серединой ворот и дальней штангой, видишь мяч и всю штрафную.",
    almostText: "Почти: вернись в зону между серединой ворот и дальней штангой, примерно в шаге от линии.",
    errorText: "Разберем: при угловом не прячься у ближней штанги и не стой в воротах - из стойки ближе к дальней штанге ты видишь мяч и успеваешь на выход.",
    hintText: "Встань между серединой ворот и дальней штангой, в шаге от линии, корпус к мячу.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "corner-left-near-post",
    title: "Угловой слева",
    category: "corner",
    difficulty: 5,
    ball: { x: 6, y: 2 },
    players: [
      { id: "a1", role: "attacker", x: 6, y: 3, hasBall: true },
      { id: "a2", role: "attacker", x: 42, y: 10 },
      { id: "d1", role: "defender", x: 47, y: 8 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    goalTarget: { side: 0.35, depth: 0.9 },
    mainErrorType: "TOO_LEFT",
    successText: "Отлично: ты держишь стойку между серединой ворот и дальней штангой и готов к подаче.",
    almostText: "Почти: направление верное, но встань между серединой ворот и дальней штангой, в шаге от линии.",
    errorText: "Разберем: при угловом не уходи к ближней штанге и не стой за линией - стойка ближе к дальней штанге дает обзор и путь к мячу.",
    hintText: "Угловой слева: встань между серединой ворот и дальней штангой, корпус к мячу.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "free-kick-right-edge",
    title: "Штрафной справа",
    category: "free_kick",
    difficulty: 4,
    ball: { x: 66, y: 21 },
    players: [
      { id: "a1", role: "attacker", x: 66, y: 21, hasBall: true },
      { id: "a2", role: "attacker", x: 71, y: 23 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    initialGoalkeeperFacing: 180,
    goalTarget: { side: -0.45, depth: 2.4 },
    freeKick: {
      recommendedWallCount: 3,
      initialWall: { count: 1, x: 50, y: 8 }
    },
    mainErrorType: "WALL_COUNT_WRONG",
    successText: "Отлично: стенка закрыла ближний угол, а ты занял открытую часть ворот.",
    almostText: "Почти: идея верная, но стенку или позицию вратаря нужно уточнить.",
    errorText: "Разберем: при штрафном справа стенка закрывает ближний угол, вратарь отвечает за открытую часть.",
    hintText: "Поставь 3 игрока в стенку между мячом и ближней штангой. Сам встань в середину свободной части ворот.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "free-kick-left-edge",
    title: "Штрафной слева",
    category: "free_kick",
    difficulty: 4,
    ball: { x: 34, y: 21 },
    players: [
      { id: "a1", role: "attacker", x: 34, y: 21, hasBall: true },
      { id: "a2", role: "attacker", x: 29, y: 23 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    initialGoalkeeperFacing: 180,
    goalTarget: { side: 0.45, depth: 2.4 },
    freeKick: {
      recommendedWallCount: 3,
      initialWall: { count: 1, x: 50, y: 8 }
    },
    mainErrorType: "WALL_COUNT_WRONG",
    successText: "Отлично: стенка закрыла ближний угол слева, а ты контролируешь открытую часть.",
    almostText: "Почти: направление верное, но стенку или позицию вратаря надо уточнить.",
    errorText: "Разберем: при штрафном слева стенка должна закрыть левую ближнюю штангу.",
    hintText: "Поставь 3 игрока в стенку на линию ближней штанги. Вратарь смещается в открытую часть ворот.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "free-kick-center",
    title: "Штрафной по центру",
    category: "free_kick",
    difficulty: 5,
    ball: { x: 50, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 50, y: 24, hasBall: true },
      { id: "a2", role: "attacker", x: 45, y: 23 },
      { id: "a3", role: "attacker", x: 55, y: 23 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    initialGoalkeeperFacing: 210,
    goalTarget: { side: -0.25, depth: 2 },
    freeKick: {
      recommendedWallCount: 4,
      initialWall: { count: 2, x: 45, y: 8 }
    },
    mainErrorType: "WALL_COUNT_WRONG",
    successText: "Отлично: стенка закрывает сторону у штанги, а ты контролируешь открытую часть и видишь мяч.",
    almostText: "Почти: решение похоже на правильное, но стенка или стойка вратаря еще неточные.",
    errorText: "Разберем: по центру нужна плотная стенка, а вратарь отвечает за открытую часть ворот и не прячется за стенкой.",
    hintText: "Выбери 4 игрока в стенке перед мячом. Сам сместись в открытую половину ворот, чтобы видеть мяч.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "high-cross-right-under-bar",
    exitDecision: "stay",
    title: "Навес справа под перекладину",
    category: "cross",
    difficulty: 4,
    ball: { x: 78, y: 9 },
    previousBall: { x: 78, y: 28 },
    players: [
      { id: "a1", role: "attacker", x: 78, y: 9, hasBall: true },
      { id: "a2", role: "attacker", x: 50, y: 7 }
    ],
    initialGoalkeeper: { x: 54, y: 8 },
    goalTarget: { side: 0, depth: 1.4 },
    mainErrorType: "TOO_HIGH",
    successText: "Верно: при высоком навесе ты держишь ворота и готов к мячу под перекладину.",
    almostText: "Почти: позиция рядом, но не уходи слишком высоко от ворот.",
    errorText: "Разберем: навес летит дугой, поэтому нельзя бросать ворота как при простреле.",
    hintText: "Высокий мяч может опуститься под перекладину. Держи ворота и корпус к мячу.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "high-cross-left-under-bar",
    exitDecision: "stay",
    title: "Навес слева под перекладину",
    category: "cross",
    difficulty: 4,
    ball: { x: 22, y: 9 },
    previousBall: { x: 22, y: 28 },
    players: [
      { id: "a1", role: "attacker", x: 22, y: 9, hasBall: true },
      { id: "a2", role: "attacker", x: 50, y: 7 }
    ],
    initialGoalkeeper: { x: 46, y: 8 },
    goalTarget: { side: 0, depth: 1.4 },
    mainErrorType: "TOO_HIGH",
    successText: "Хорошо: ты не выбежал на навес и держишь мяч под перекладиной.",
    almostText: "Почти: останься спокойнее в воротах и развернись к мячу.",
    errorText: "Разберем: высокий навес слева может опуститься в ворота.",
    hintText: "Не играй навес как низкий прострел. Сначала контролируй ворота.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "high-cross-far-post",
    exitDecision: "stay",
    title: "Навес на дальнюю штангу",
    category: "cross",
    difficulty: 5,
    ball: { x: 82, y: 12 },
    previousBall: { x: 82, y: 30 },
    players: [
      { id: "a1", role: "attacker", x: 82, y: 12, hasBall: true },
      { id: "a2", role: "attacker", x: 40, y: 6 },
      { id: "d1", role: "defender", x: 45, y: 7 }
    ],
    initialGoalkeeper: { x: 55, y: 8 },
    goalTarget: { side: -0.5, depth: 1.6 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: ты сместился к дальней штанге, но не бросил ворота.",
    almostText: "Почти: направление правильное, но точку у дальней штанги выбери точнее.",
    errorText: "Разберем: дальняя штанга становится главной зоной угрозы.",
    hintText: "Мяч летит через ворота. Сместись к дальней штанге, но не уходи за линию.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "high-cross-crowd",
    exitDecision: "stay",
    title: "Навес в толпу игроков",
    category: "cross",
    difficulty: 5,
    ball: { x: 28, y: 13 },
    previousBall: { x: 28, y: 31 },
    players: [
      { id: "a1", role: "attacker", x: 28, y: 13, hasBall: true },
      { id: "a2", role: "attacker", x: 48, y: 8 },
      { id: "a3", role: "attacker", x: 55, y: 9 },
      { id: "d1", role: "defender", x: 50, y: 8 },
      { id: "d2", role: "defender", x: 57, y: 9 }
    ],
    initialGoalkeeper: { x: 50, y: 8 },
    goalTarget: { side: 0, depth: 1.8 },
    mainErrorType: "TOO_HIGH",
    successText: "Верно: при толпе игроков ты держишь рабочую позицию и не вылетаешь вслепую.",
    almostText: "Почти: позиция близкая, но выход должен быть спокойнее.",
    errorText: "Разберем: в толпу нельзя выбегать без уверенности, иначе ворота пустые.",
    hintText: "Если траектория спорная и впереди много игроков, сначала держи ворота.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "high-cross-clean-right",
    title: "Чистая подача справа во вратарскую",
    category: "cross",
    exitDecision: "go",
    difficulty: 4,
    ball: { x: 80, y: 18 },
    previousBall: { x: 80, y: 32 },
    players: [
      { id: "a1", role: "attacker", x: 80, y: 18, hasBall: true },
      { id: "a2", role: "attacker", x: 58, y: 16 },
      { id: "d1", role: "defender", x: 54, y: 14 }
    ],
    initialGoalkeeper: { x: 50, y: 1 },
    goalTarget: { side: 0.1, depth: 3.2 },
    mainErrorType: "TOO_DEEP",
    successText: "Отлично: подача чистая, и ты решил выйти - мяч во вратарской должен быть твоим.",
    almostText: "Почти: решение выйти верное, точку выхода можно выбрать увереннее.",
    errorText: "Разберем: траектория чистая, соперников рядом нет - такой мяч вратарь забирает сам.",
    hintText: "Никто не мешает, мяч летит во вратарскую: решай выходить и забирай подачу.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "high-cross-clean-left",
    title: "Чистая подача слева во вратарскую",
    category: "cross",
    exitDecision: "go",
    difficulty: 4,
    ball: { x: 20, y: 18 },
    previousBall: { x: 20, y: 32 },
    players: [
      { id: "a1", role: "attacker", x: 20, y: 18, hasBall: true },
      { id: "a2", role: "attacker", x: 42, y: 16 },
      { id: "d1", role: "defender", x: 46, y: 14 }
    ],
    initialGoalkeeper: { x: 50, y: 1 },
    goalTarget: { side: -0.1, depth: 3.2 },
    mainErrorType: "TOO_DEEP",
    successText: "Отлично: чистая траектория - ты вышел и хозяйничаешь во вратарской.",
    almostText: "Почти: решение выйти правильное, добавь уверенности в точке выхода.",
    errorText: "Разберем: когда подача чистая, оставаться на линии - значит отдать мяч сопернику.",
    hintText: "Свободная вратарская и чистая траектория: выходи на мяч.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "corner-right-open-far-post",
    title: "Угловой справа: открытое поле",
    category: "corner",
    difficulty: 5,
    ball: { x: 94, y: 2 },
    players: [
      { id: "a1", role: "attacker", x: 94, y: 3, hasBall: true },
      { id: "a2", role: "attacker", x: 54, y: 8 },
      { id: "d1", role: "defender", x: 50, y: 8 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    goalTarget: { side: -0.35, depth: 1 },
    mainErrorType: "TOO_RIGHT",
    successText: "Отлично: ты занял дальнюю стартовую зону, видишь мяч и контролируешь ворота.",
    almostText: "Почти: сместись в дальнюю стартовую зону и держи корпус к мячу.",
    errorText: "Разберем: при этой подаче справа стартуй в зоне, где виден мяч, ворота под контролем и есть путь к мячу.",
    hintText: "Открытое поле: выбери дальнюю стартовую зону, но не проваливайся за линию ворот.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "corner-left-open-far-post",
    title: "Угловой слева: открытое поле",
    category: "corner",
    difficulty: 5,
    ball: { x: 6, y: 2 },
    players: [
      { id: "a1", role: "attacker", x: 6, y: 3, hasBall: true },
      { id: "a2", role: "attacker", x: 46, y: 8 },
      { id: "d1", role: "defender", x: 50, y: 8 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    goalTarget: { side: 0.35, depth: 1 },
    mainErrorType: "TOO_LEFT",
    successText: "Верно: при этой подаче слева ты занял дальнюю стартовую зону.",
    almostText: "Почти: дальняя зона рядом, но стартовую позицию можно выбрать спокойнее.",
    errorText: "Разберем: при этой подаче слева стартуй в зоне, где виден мяч, ворота под контролем и есть путь к мячу.",
    hintText: "Выбери дальнюю стартовую зону справа, но не проваливайся за линию ворот.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "corner-right-indoor-middle",
    title: "Угловой справа: зал",
    category: "corner",
    difficulty: 4,
    ball: { x: 94, y: 2 },
    players: [
      { id: "a1", role: "attacker", x: 94, y: 3, hasBall: true },
      { id: "a2", role: "attacker", x: 58, y: 8 }
    ],
    initialGoalkeeper: { x: 56, y: 0 },
    pitchPresetOverride: "futsal",
    goalTarget: { side: 0, depth: 0.7 },
    mainErrorType: "TOO_RIGHT",
    successText: "Хорошо: в зале ты держишь середину ворот и готов к быстрой подаче.",
    almostText: "Почти: вернись ближе к середине ворот.",
    errorText: "Разберем: в зале угловой быстрее, поэтому стартовая позиция ближе к середине.",
    hintText: "Зал или хоккейная площадка: не прячься у стойки, держи середину.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "corner-left-indoor-middle",
    title: "Угловой слева: зал",
    category: "corner",
    difficulty: 4,
    ball: { x: 6, y: 2 },
    players: [
      { id: "a1", role: "attacker", x: 6, y: 3, hasBall: true },
      { id: "a2", role: "attacker", x: 42, y: 8 }
    ],
    initialGoalkeeper: { x: 44, y: 0 },
    pitchPresetOverride: "futsal",
    goalTarget: { side: 0, depth: 0.7 },
    mainErrorType: "TOO_LEFT",
    successText: "Верно: в зале ты держишь середину ворот и видишь быстрый розыгрыш.",
    almostText: "Почти: стой ближе к центру ворот.",
    errorText: "Разберем: в зале при угловом не нужно уходить к стойке как на большом поле.",
    hintText: "Зал: середина ворот важнее дальней стойки.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "free-kick-close-center",
    title: "Близкий штрафной по центру",
    category: "free_kick",
    difficulty: 5,
    ball: { x: 50, y: 15 },
    players: [
      { id: "a1", role: "attacker", x: 50, y: 15, hasBall: true },
      { id: "a2", role: "attacker", x: 45, y: 16 },
      { id: "a3", role: "attacker", x: 55, y: 16 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    goalTarget: { side: -0.3, depth: 1.6 },
    freeKick: {
      recommendedWallCount: 4,
      initialWall: { count: 2, x: 44, y: 7 }
    },
    mainErrorType: "WALL_COUNT_WRONG",
    successText: "Отлично: близкий штрафной требует плотной стенки и спокойной позиции вратаря.",
    almostText: "Почти: решение рядом, но стенку или глубину нужно уточнить.",
    errorText: "Разберем: при близком штрафном нельзя выбегать далеко и нельзя ставить редкую стенку.",
    hintText: "Близко к воротам: 4 игрока в стенке, вратарь держит открытую часть и не уходит высоко.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "free-kick-very-wide-right",
    title: "Очень боковой штрафной справа",
    category: "free_kick",
    difficulty: 4,
    ball: { x: 82, y: 16 },
    players: [
      { id: "a1", role: "attacker", x: 82, y: 16, hasBall: true },
      { id: "a2", role: "attacker", x: 74, y: 18 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    goalTarget: { side: -0.2, depth: 2 },
    freeKick: {
      recommendedWallCount: 2,
      initialWall: { count: 4, x: 54, y: 8 }
    },
    mainErrorType: "WALL_COUNT_WRONG",
    successText: "Верно: с очень бокового штрафного стенка меньше, а вратарь контролирует открытую часть.",
    almostText: "Почти: не забирай лишних игроков в стенку и уточни ее линию.",
    errorText: "Разберем: очень боковой штрафной не требует большой стенки.",
    hintText: "Справа и остро: 2 игрока в стенке, ближняя траектория закрыта, вратарь видит мяч.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "free-kick-short-pass-threat",
    title: "Штрафной с розыгрышем",
    category: "free_kick",
    difficulty: 5,
    ball: { x: 42, y: 22 },
    players: [
      { id: "a1", role: "attacker", x: 42, y: 22, hasBall: true },
      { id: "a2", role: "attacker", x: 55, y: 18 },
      { id: "a3", role: "attacker", x: 62, y: 13 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    goalTarget: { side: 0.5, depth: 2.4 },
    freeKick: {
      recommendedWallCount: 3,
      initialWall: { count: 1, x: 50, y: 9 }
    },
    mainErrorType: "WALL_POSITION_WRONG",
    successText: "Хорошо: стенка закрывает удар, а ты не потерял возможный пас вправо.",
    almostText: "Почти: стенка или позиция вратаря еще немного спорные.",
    errorText: "Разберем: при розыгрыше важно закрыть удар, но не застыть за стенкой.",
    hintText: "Поставь 3 в стенку, но сам стой так, чтобы видеть мяч и пас в открытую зону.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "free-kick-small-goal",
    title: "Штрафной на маленькие ворота",
    category: "free_kick",
    difficulty: 4,
    ball: { x: 58, y: 18 },
    players: [
      { id: "a1", role: "attacker", x: 58, y: 18, hasBall: true },
      { id: "a2", role: "attacker", x: 63, y: 18 }
    ],
    initialGoalkeeper: { x: 50, y: 0 },
    pitchPresetOverride: "5v5",
    goalTarget: { side: -0.45, depth: 1.8 },
    freeKick: {
      recommendedWallCount: 2,
      initialWall: { count: 4, x: 50, y: 8 }
    },
    mainErrorType: "WALL_COUNT_WRONG",
    successText: "Отлично: на маленькие ворота стенка компактная, а вратарь не теряет обзор.",
    almostText: "Почти: идея верная, но маленькие ворота требуют точности.",
    errorText: "Разберем: на маленьком поле нельзя ставить слишком большую стенку.",
    hintText: "Маленькие ворота: 2 игрока в стенке, вратарь видит мяч и открытую часть.",
    evaluationMode: "zone",
    explanationLayers: layers
  },
  {
    id: "rebound-center-to-right",
    title: "Отскок после сейва вправо",
    category: "pass_reposition",
    scenarioType: "pass_or_cutback",
    difficulty: 4,
    ball: { x: 62, y: 12 },
    previousBall: { x: 50, y: 20 },
    players: [
      { id: "a1", role: "attacker", x: 50, y: 22 },
      { id: "a2", role: "attacker", x: 62, y: 14, hasBall: true }
    ],
    initialGoalkeeper: { x: 50, y: 3 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: после отскока ты мгновенно нашел новую линию мяча и закрыл добивание.",
    almostText: "Почти: ты начал перестроение к отскоку, но линию нового мяча можно занять точнее.",
    errorText: "Разберем: мяч отскочил вправо, а позиция осталась от первого удара - добивание идет в открытые ворота.",
    hintText: "После сейва мяч живой. Сразу ищи новую линию мяча и перестраивайся.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "rebound-right-to-left",
    title: "Отскок на дальнюю сторону",
    category: "pass_reposition",
    scenarioType: "pass_or_cutback",
    difficulty: 5,
    ball: { x: 40, y: 10 },
    previousBall: { x: 64, y: 16 },
    players: [
      { id: "a1", role: "attacker", x: 64, y: 18 },
      { id: "a2", role: "attacker", x: 40, y: 12, hasBall: true },
      { id: "d1", role: "defender", x: 52, y: 12 }
    ],
    initialGoalkeeper: { x: 58, y: 4 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: отскок ушел на другую сторону, и ты успел переставить точку ног на новую линию.",
    almostText: "Почти: направление перестроения верное, дойди до линии нового мяча.",
    errorText: "Разберем: после отскока на дальнюю сторону нельзя оставаться у старой штанги.",
    hintText: "Мяч отскочил через штрафную. Новая линия мяча важнее старой позиции.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "rebound-close-center",
    title: "Добивание с близкой точки",
    category: "pass_reposition",
    scenarioType: "pass_or_cutback",
    difficulty: 5,
    ball: { x: 47, y: 8 },
    previousBall: { x: 55, y: 14 },
    players: [
      { id: "a1", role: "attacker", x: 55, y: 16 },
      { id: "a2", role: "attacker", x: 47, y: 10, hasBall: true }
    ],
    initialGoalkeeper: { x: 54, y: 3 },
    mainErrorType: "NOT_ADJUSTED_AFTER_PASS",
    successText: "Отлично: при близком добивании ты занял новую линию и не вылетел навстречу вслепую.",
    almostText: "Почти: линия нового мяча рядом, добавь точности по глубине.",
    errorText: "Разберем: добивание идет с новой точки - нужно быстро сместиться и остаться в рабочей стойке.",
    hintText: "Близкое добивание: новая линия мяча плюс спокойная глубина.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "sweeper-long-ball-center",
    title: "Передача за спину защиты",
    category: "depth",
    scenarioType: "sweeper_position",
    difficulty: 4,
    ball: { x: 50, y: 62 },
    players: [
      { id: "a1", role: "attacker", x: 50, y: 64, hasBall: true },
      { id: "d1", role: "defender", x: 44, y: 42 },
      { id: "d2", role: "defender", x: 56, y: 40 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "TOO_DEEP",
    successText: "Отлично: защита играет высоко, и ты страхуешь пространство за ее спиной.",
    almostText: "Почти: идея верная, но для страховки длинной передачи выйди еще смелее.",
    errorText: "Разберем: когда мяч далеко и защита высоко, вратарь на линии ворот не успеет к передаче за спину.",
    hintText: "Мяч далеко, защита высоко: выйди из ворот и страхуй зону за защитниками.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "sweeper-long-ball-right",
    title: "Длинная передача справа",
    category: "depth",
    scenarioType: "sweeper_position",
    difficulty: 5,
    ball: { x: 63, y: 58 },
    players: [
      { id: "a1", role: "attacker", x: 63, y: 60, hasBall: true },
      { id: "a2", role: "attacker", x: 45, y: 46 },
      { id: "d1", role: "defender", x: 47, y: 42 },
      { id: "d2", role: "defender", x: 58, y: 40 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "TOO_DEEP",
    successText: "Отлично: высокая страхующая позиция по линии мяча - передача за спину уже не страшна.",
    almostText: "Почти: глубина рабочая, но держись точнее линии мяча.",
    errorText: "Разберем: при длинной передаче из глубины вратарь - последний защитник, из ворот выходить обязательно.",
    hintText: "Смотри на игрока с мячом справа и страхуй зону за защитой по линии мяча.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "penalty-center",
    title: "Пенальти",
    category: "penalty",
    scenarioType: "penalty",
    difficulty: 3,
    // Точка мяча подгоняется под точку пенальти активного пресета в App.
    ball: { x: 50, y: 15 },
    players: [{ id: "a1", role: "attacker", x: 50, y: 19, hasBall: true }],
    initialGoalkeeper: { x: 50, y: 6 },
    goalTarget: { side: 0, depth: 0.35 },
    mainErrorType: "TOO_HIGH",
    successText: "Отлично: ты по центру и на линии ворот, как требуют правила, и готов оттолкнуться в любой угол.",
    almostText: "Почти: держись середины ворот и оставайся на линии до самого удара.",
    errorText: "Разберем: по правилам до удара хотя бы часть одной ноги должна оставаться на линии ворот. Если выйти раньше, пенальти могут заставить перебить.",
    hintText: "Правило пенальти: до удара оставайся на линии ворот. Встань по центру и держи корпус к мячу.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  }
];

const reactionLevels: Level[] = [
  {
    id: "reaction-easy-center-far",
    title: "Реакция: дальний мяч по центру",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 2,
    reactionDifficulty: "easy",
    reactionTimeSeconds: 5,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    ball: { x: 50, y: 42 },
    players: [{ id: "a1", role: "attacker", x: 50, y: 42 }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "TOO_DEEP",
    successText: "Отлично: ты быстро прочитал мяч по центру и вышел на рабочую глубину.",
    almostText: "Почти: линия верная, но глубину или готовность можно сделать точнее.",
    errorText: "Разберем: дальний центральный мяч требует смелее выйти из ворот, но остаться по центру.",
    hintText: "Когда мяч появился по центру и далеко, держи центр и выйди выше.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-easy-center-close",
    title: "Реакция: близкий мяч по центру",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 3,
    reactionDifficulty: "easy",
    reactionTimeSeconds: 5,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    ball: { x: 50, y: 13 },
    players: [{ id: "a1", role: "attacker", x: 50, y: 13 }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "TOO_HIGH",
    successText: "Верно: ты остался по центру и не выбежал слишком далеко на близкий мяч.",
    almostText: "Почти: позиция рабочая, но остановись чуть спокойнее.",
    errorText: "Разберем: близко по центру нельзя улетать вперед, иначе нападающий обыграет или перебросит.",
    hintText: "Близкий мяч по центру: держи центр и умеренную глубину.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-easy-right-half",
    title: "Реакция: мяч справа у штрафной",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 3,
    reactionDifficulty: "easy",
    reactionTimeSeconds: 5,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    ball: { x: 68, y: 24 },
    players: [{ id: "a1", role: "attacker", x: 68, y: 24 }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Отлично: после появления мяча справа ты закрыл ближний угол.",
    almostText: "Почти: смещение к мячу верное, осталось уточнить глубину.",
    errorText: "Разберем: мяч справа, поэтому центральная позиция открывает ближнюю штангу.",
    hintText: "Мяч справа - сместись вправо и поверни корпус к мячу.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-easy-left-half",
    title: "Реакция: мяч слева у штрафной",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 3,
    reactionDifficulty: "easy",
    reactionTimeSeconds: 5,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    ball: { x: 32, y: 24 },
    players: [{ id: "a1", role: "attacker", x: 32, y: 24 }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Верно: ты быстро сместился к левому мячу и закрыл ближнюю штангу.",
    almostText: "Почти: направление верное, но позиция может быть точнее.",
    errorText: "Разберем: при мяче слева сначала закрывается левый ближний угол.",
    hintText: "Мяч слева - сместись влево по линии мяча.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-easy-right-byline",
    title: "Реакция: острый угол справа",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 4,
    reactionDifficulty: "easy",
    reactionTimeSeconds: 5,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    ball: { x: 84, y: 11 },
    players: [{ id: "a1", role: "attacker", x: 84, y: 11 }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Хорошо: ты закрыл правую ближнюю зону и не провалился в ворота.",
    almostText: "Почти: ближняя зона под контролем, но не перебеги к штанге.",
    errorText: "Разберем: с острого угла справа нельзя оставлять ближнюю штангу открытой.",
    hintText: "Острый угол справа: ближняя штанга важнее центра ворот.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-easy-left-byline",
    title: "Реакция: острый угол слева",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 4,
    reactionDifficulty: "easy",
    reactionTimeSeconds: 5,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    ball: { x: 16, y: 11 },
    players: [{ id: "a1", role: "attacker", x: 16, y: 11 }],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Отлично: ты успел к левой ближней зоне и держишь корпус к мячу.",
    almostText: "Почти: идея верная, но глубину нужно сделать спокойнее.",
    errorText: "Разберем: с острого угла слева первый риск - ближняя штанга.",
    hintText: "Острый угол слева: сместись к мячу, но не заходи в ворота.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-medium-right-active",
    title: "Реакция: справа или центр?",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 3,
    reactionDifficulty: "medium",
    reactionTimeSeconds: 4,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    reactionPass: { toPlayerId: "a2", atRemainingSeconds: 2 },
    ball: { x: 70, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 70, y: 24 },
      { id: "a2", role: "attacker", x: 50, y: 26 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "WRONG_BALL_OWNER",
    successText: "Верно: ты вел мяч глазами и после паса успел перестроиться на новую линию.",
    almostText: "Почти: главную угрозу выбрал правильно, но позицию можно уточнить.",
    errorText: "Разберем: следи за активным мячом - после паса позиция строится заново.",
    hintText: "Смотри, у кого мяч. Он может уйти в пас - будь готов перестроиться.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-medium-center-active-right-decoy",
    title: "Реакция: центр вместо правого",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 3,
    reactionDifficulty: "medium",
    reactionTimeSeconds: 4,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a2",
    ball: { x: 50, y: 25 },
    players: [
      { id: "a1", role: "attacker", x: 70, y: 24 },
      { id: "a2", role: "attacker", x: 50, y: 25 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "WRONG_BALL_OWNER",
    successText: "Отлично: ты не купился на правого игрока и вернулся к центральной линии мяча.",
    almostText: "Почти: центр выбран верно, но глубина требует поправки.",
    errorText: "Разберем: мяч появился в центре, поэтому уход к правому игроку открывает ворота.",
    hintText: "Если мяч в центре, держи центр ворот.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-medium-left-active",
    title: "Реакция: слева или центр?",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 3,
    reactionDifficulty: "medium",
    reactionTimeSeconds: 4,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    reactionPass: { toPlayerId: "a2", atRemainingSeconds: 2 },
    ball: { x: 30, y: 24 },
    players: [
      { id: "a1", role: "attacker", x: 30, y: 24 },
      { id: "a2", role: "attacker", x: 50, y: 26 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "WRONG_BALL_OWNER",
    successText: "Верно: ты держал мяч глазами и после передачи занял новую линию.",
    almostText: "Почти: смещение верное, осталось чуть точнее выбрать глубину.",
    errorText: "Разберем: мяч ушел в пас - позиция строится от новой точки мяча.",
    hintText: "Мяч слева, но может уйти в пас. Веди мяч глазами до самого удара.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-medium-center-active-left-decoy",
    title: "Реакция: центр вместо левого",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 3,
    reactionDifficulty: "medium",
    reactionTimeSeconds: 4,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a2",
    ball: { x: 50, y: 25 },
    players: [
      { id: "a1", role: "attacker", x: 30, y: 24 },
      { id: "a2", role: "attacker", x: 50, y: 25 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "WRONG_BALL_OWNER",
    successText: "Отлично: ты прочитал центральный мяч и не ушел на игрока без мяча.",
    almostText: "Почти: направление правильное, но точка ног еще спорная.",
    errorText: "Разберем: когда мяч в центре, фланговый игрок без мяча не должен увести вратаря.",
    hintText: "Центральный мяч - центральная линия.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-medium-byline-active",
    title: "Реакция: мяч у лицевой",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 4,
    reactionDifficulty: "medium",
    reactionTimeSeconds: 4,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    ball: { x: 82, y: 10 },
    players: [
      { id: "a1", role: "attacker", x: 82, y: 10 },
      { id: "a2", role: "attacker", x: 54, y: 20 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Хорошо: ты закрыл ближнюю штангу у лицевой и остался готов к прострелу.",
    almostText: "Почти: ближний угол почти закрыт, но не перебеги из ворот.",
    errorText: "Разберем: у лицевой линии сначала контролируй ближнюю штангу и прострел.",
    hintText: "Мяч у лицевой - ближняя штанга, но без прыжка на игрока в центре.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-medium-cutback-active",
    title: "Реакция: откат под удар",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 4,
    reactionDifficulty: "medium",
    reactionTimeSeconds: 4,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a2",
    ball: { x: 54, y: 20 },
    players: [
      { id: "a1", role: "attacker", x: 82, y: 10 },
      { id: "a2", role: "attacker", x: 54, y: 20 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "WRONG_BALL_OWNER",
    successText: "Отлично: ты сместился от ближней штанги к новой линии мяча после отката.",
    almostText: "Почти: новая линия выбрана, но позицию можно сделать устойчивее.",
    errorText: "Разберем: откат дает лучший угол для удара, старая позиция у штанги уже не спасает.",
    hintText: "Если мяч появился под откат, вернись к новой линии мяча.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-hard-arc-center",
    title: "Реакция: трое по дуге, мяч в центре",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 4,
    reactionDifficulty: "hard",
    reactionTimeSeconds: 3,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a2",
    reactionPass: { toPlayerId: "a3", atRemainingSeconds: 2 },
    ball: { x: 50, y: 27 },
    players: [
      { id: "a1", role: "attacker", x: 32, y: 25 },
      { id: "a2", role: "attacker", x: 50, y: 27 },
      { id: "a3", role: "attacker", x: 68, y: 25 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "WRONG_BALL_OWNER",
    successText: "Верно: ты прочитал перегруз и после паса направо успел на новую линию.",
    almostText: "Почти: главная угроза прочитана, но глубина или корпус требуют точности.",
    errorText: "Разберем: мяч ушел в пас на фланг - нельзя оставаться на старой линии.",
    hintText: "Трое по дуге: найди мяч и будь готов, что он уйдет в пас.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-hard-arc-right",
    title: "Реакция: трое по дуге, мяч справа",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 4,
    reactionDifficulty: "hard",
    reactionTimeSeconds: 3,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a3",
    ball: { x: 68, y: 25 },
    players: [
      { id: "a1", role: "attacker", x: 32, y: 25 },
      { id: "a2", role: "attacker", x: 50, y: 27 },
      { id: "a3", role: "attacker", x: 68, y: 25 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Хорошо: ты выбрал правого игрока с мячом и не потерял готовность к пасу.",
    almostText: "Почти: линия мяча почти найдена, но позиция еще не идеальна.",
    errorText: "Разберем: мяч справа, поэтому ближний угол справа закрывается первым.",
    hintText: "Активный справа - сместись вправо, центр держи в поле зрения.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-hard-arc-left",
    title: "Реакция: трое по дуге, мяч слева",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 4,
    reactionDifficulty: "hard",
    reactionTimeSeconds: 3,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    ball: { x: 32, y: 25 },
    players: [
      { id: "a1", role: "attacker", x: 32, y: 25 },
      { id: "a2", role: "attacker", x: 50, y: 27 },
      { id: "a3", role: "attacker", x: 68, y: 25 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Верно: ты быстро перестроился к левому мячу и закрыл ближний угол.",
    almostText: "Почти: смещение верное, но глубину можно выбрать точнее.",
    errorText: "Разберем: если мяч слева, нельзя оставаться в центре из-за игроков справа.",
    hintText: "Активный слева - новая линия мяча слева.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-hard-right-flank",
    title: "Реакция: фланг, центр и дальняя",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 5,
    reactionDifficulty: "hard",
    reactionTimeSeconds: 3,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a1",
    reactionPass: { toPlayerId: "a2", atRemainingSeconds: 2 },
    ball: { x: 82, y: 13 },
    players: [
      { id: "a1", role: "attacker", x: 82, y: 13 },
      { id: "a2", role: "attacker", x: 54, y: 20 },
      { id: "a3", role: "attacker", x: 28, y: 9 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "NEAR_POST_OPEN",
    successText: "Хорошо: ты закрыл фланг, а после отката в центр успел перестроиться.",
    almostText: "Почти: главная угроза выбрана, но позиция чуть спорная.",
    errorText: "Разберем: после отката в центр старая фланговая позиция открывает ворота.",
    hintText: "Правый фланг с мячом, но следи: мяч может уйти откатом в центр.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-hard-center-from-left",
    title: "Реакция: передача в центр",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 5,
    reactionDifficulty: "hard",
    reactionTimeSeconds: 3,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a2",
    ball: { x: 50, y: 21 },
    players: [
      { id: "a1", role: "attacker", x: 18, y: 13 },
      { id: "a2", role: "attacker", x: 50, y: 21 },
      { id: "a3", role: "attacker", x: 78, y: 11 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "WRONG_BALL_OWNER",
    successText: "Отлично: ты вернулся к центральной линии мяча после активации центра.",
    almostText: "Почти: центр выбран правильно, но нужно устойчивее остановиться.",
    errorText: "Разберем: когда мяч появился в центре, фланговая позиция больше не закрывает ворота.",
    hintText: "После появления мяча в центре держи центральную линию и рабочую глубину.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  },
  {
    id: "reaction-hard-switch-left",
    title: "Реакция: смена стороны налево",
    stage: "reaction_to_ball_owner",
    category: "reaction",
    scenarioType: "reaction_to_ball_owner",
    difficulty: 5,
    reactionDifficulty: "hard",
    reactionTimeSeconds: 3,
    ballOwnerActivationDelayMs: 1200,
    activatedBallOwnerId: "a3",
    ball: { x: 24, y: 20 },
    players: [
      { id: "a1", role: "attacker", x: 76, y: 18 },
      { id: "a2", role: "attacker", x: 62, y: 24 },
      { id: "a3", role: "attacker", x: 24, y: 20 }
    ],
    initialGoalkeeper: { x: 50, y: 2 },
    mainErrorType: "WRONG_BALL_OWNER",
    successText: "Верно: ты не завис на стороне перегруза и перестроился к мячу слева.",
    almostText: "Почти: направление правильное, но ближний угол можно закрыть надежнее.",
    errorText: "Разберем: расстановка справа отвлекает, но после появления мяча слева меняется вся геометрия.",
    hintText: "Не угадывай по расстановке. Смотри, где появился мяч.",
    evaluationMode: "hybrid",
    explanationLayers: layers
  }
];

export const levels: Level[] = [...baseLevels, ...extraLevels, ...reactionLevels];
